added solutions for homework 03.
js-tasks-ru/nodejs-20220704_ilaltim pull request #3
Opened 2022-07-12 12:23 UTC by chertt007

added LimitSizeStream solution
added file-server-get solution

2022-07-12 12:25 UTC, jsru commented
Добавляю преподавателя (@tadjik1) для код-ревью.

2022-07-12 13:29 UTC, tadjik1 commented on 03-streams/01-limit-size-stream/LimitSizeStream.js
> +      this.destroy(new LimitExceededError());
можно не вызывать destroy, а передать аргумент ошибки в callback - `callback(new LimitExceededError())`, так будет правильнее, .destroy как правило для вызыва внешними клиентами

2022-07-12 13:30 UTC, tadjik1 commented on 03-streams/03-file-server-get/server.js
> +        if (pathname.split("/").length > 1) {
правильнее вынести эту проверку, и выполнять ее до создания стрима. иначе если файл будет на диске - то он будет отдан клиенту без ошибок.

2022-07-12 13:31 UTC, tadjik1 requested changes
@chertt007 в целом выполнено верно, но я отметил пару мест в коде, где стоит поправить реализацию

2022-07-13 08:04 UTC, jsru commented
Добавляю преподавателя (@tadjik1) для код-ревью.

2022-07-13 09:30 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @tadjik1

2022-07-14 04:52 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @tadjik1

2022-07-14 04:52 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @tadjik1

2022-07-16 14:43 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @tadjik1

2022-07-16 15:31 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @tadjik1

2022-07-17 08:35 UTC, tadjik1 approved these changes
В целом все выполнено хорошо. Один небольшой нюанс про валидатор - в обработке ситуации со слишком большим числом есть ошибка, похоже ваши тесты ещё не смогли выявить :)

2022-07-17 08:35 UTC, tadjik1 commented on 03-streams/05-file-server-delete/server.js
> +    res.end("nested folders are unsuported");
Вот тут лучше добавить return, ведь выполнение функции продолжится и это может привести к плохим последствиям

2022-07-17 08:36 UTC, merged